module.exports = {
    Base: require('./utils/base'),
    Spam: require('./utils/spam'),
    MyIP: require('./utils/ip'),
    Proxy: require('./utils/proxy'),
    Hilih: require('./utils/hilih'),
    Faker: require('./utils/faker'),
    Nulis: require('./utils/nulis'),
    WPUser: require('./utils/wpuser'),
    Corona: require('./utils/corona'),
    Headers: require('./utils/headers'),
    HashGen: require('./utils/hash'),
    Dicoding: require('./utils/dicoding'),
    IpLookup: require('./utils/iplookup'),
    hashIdent: require('./utils/hash_ident'),
}
