module.exports = {
    Base: require('./utils/base'),
    Spam: require('./utils/spamwa'),
    MyIP: require('./utils/ip'),
    Proxy: require('./utils/proxy'),
    Hilih: require('./utils/hilih'),
    Faker: require('./utils/faker'),
    Nulis: require('./utils/nulis'),
    WPUser: require('./utils/wpuser'),
    Corona: require('./utils/corona'),
    Headers: require('./utils/headers'),
    HashGen: require('./utils/hash'),
    Dicoding: require('./utils/dicoding'),
    IpLookup: require('./utils/iplookup'),
    hashIdent: require('./utils/hash_ident'),
	Tiktok: require('./utils/tiktok'),
	KBBI: require('./utils/KBBI'),
	Lirik: require('./utils/lirik'),
	Pornhub: require('./utils/pornhub'),
	RandomP: require('./utils/randomp'),
	RandomH: require('./utils/randomh'),
	Nhentai: require('./utils/nhentai'),
	Ushort: require('./utils/ushort'),
	Covid19: require('./utils/covid'),
	IG: require('./utils/ig'),
	IGStalk: require('./utils/igs'),
	Gempa: require('./utils/gempa'),
	Cekresi: require('./utils/cekresi'),
	Cuaca: require('./utils/cuaca'),
	Nekopoi: require('./utils/nekopoi'),
	TTSCL : require("./utils/ttscaklontong.js"),
	GH : require("./utils/github.js"),
	FilmApik : require("./utils/filmapik.js"),
	ytDownlodMp3 : require("./utils/youtubemp3.js"),
	ytDownlodMp4 : require("./utils/youtubemp4.js"),
	Crypto : require("./utils/crypto.js")
}
